In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
yield_df = pd.read_csv(r"data\CropYield\yield_df.csv")
rainfall = pd.read_csv(r"data\CropYield\rainfall.csv")
temperature = pd.read_csv(r"data\CropYield\temp.csv")
pesticides = pd.read_csv(r"data\CropYield\pesticides.csv")
yield_data = pd.read_csv(r"data\CropYield\yield.csv")

In [3]:
datasets = {
    "yield_df": yield_df,
    "rainfall": rainfall,
    "temperature": temperature,
    "pesticides": pesticides,
    "yield": yield_data
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("-"*30)
    print("Rows :", df.shape[0])
    print("Columns :", df.shape[1])

yield_df
------------------------------
Rows : 28242
Columns : 8

rainfall
------------------------------
Rows : 6727
Columns : 3

temperature
------------------------------
Rows : 71311
Columns : 3

pesticides
------------------------------
Rows : 4349
Columns : 7

yield
------------------------------
Rows : 56717
Columns : 12

In [4]:
yield_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     28242 non-null  int64
 1   Area                           28242 non-null  object
 2   Item                           28242 non-null  object
 3   Year                           28242 non-null  int64
 4   hg/ha_yield                    28242 non-null  int64
 5   average_rain_fall_mm_per_year  28242 non-null  float64
 6   pesticides_tonnes              28242 non-null  float64
 7   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(3), object(2)
memory usage: 1.7+ MB

In [5]:
yield_df.isnull().sum()

Unnamed: 0                       0
Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64

In [6]:
yield_df.duplicated().sum()

np.int64(0)

In [7]:
print("Countries :", yield_df["Area"].nunique())

print("Crops :", yield_df["Item"].nunique())

print("Years :", yield_df["Year"].nunique())

Countries : 101
Crops : 10
Years : 23

In [8]:
yield_df.describe(include="all")

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
count,28242.000000,28242,28242,28242.000000,28242.000000,28242.00000,28242.000000,28242.000000
unique,NaN,101,10,NaN,NaN,NaN,NaN,NaN
top,NaN,India,Potatoes,NaN,NaN,NaN,NaN,NaN
freq,NaN,4048,4276,NaN,NaN,NaN,NaN,NaN
mean,14120.500000,NaN,NaN,2001.544296,77053.332094,1149.05598,37076.909344,20.542627
std,8152.907488,NaN,NaN,7.051905,84956.612897,709.81215,59958.784665,6.312051
min,0.000000,NaN,NaN,1990.000000,50.000000,51.00000,0.040000,1.300000
25%,7060.250000,NaN,NaN,1995.000000,19919.250000,593.00000,1702.000000,16.702500
50%,14120.500000,NaN,NaN,2001.000000,38295.000000,1083.00000,17529.440000,21.510000
75%,21180.750000,NaN,NaN,2008.000000,104676.750000,1668.00000,48687.880000,26.000000
max,28241.000000,NaN,NaN,2013.000000,501412.000000,3240.00000,367778.000000,30.650000

In [9]:
yield_df.drop("Unnamed: 0", axis=1, inplace=True)

yield_df.head()

,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

In [10]:
yield_df.columns

Index(['Area', 'Item', 'Year', 'hg/ha_yield', 'average_rain_fall_mm_per_year',
       'pesticides_tonnes', 'avg_temp'],
      dtype='object')

In [11]:
print("Countries:")
print(sorted(yield_df["Area"].unique()))

print("\nNumber of Countries:", yield_df["Area"].nunique())

Countries:
['Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Botswana', 'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cameroon', 'Canada', 'Central African Republic', 'Chile', 'Colombia', 'Croatia', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Eritrea', 'Estonia', 'Finland', 'France', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'India', 'Indonesia', 'Iraq', 'Ireland', 'Italy', 'Jamaica', 'Japan', 'Kazakhstan', 'Kenya', 'Latvia', 'Lebanon', 'Lesotho', 'Libya', 'Lithuania', 'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania', 'Mauritius', 'Mexico', 'Montenegro', 'Morocco', 'Mozambique', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Norway', 'Pakistan', 'Papua New Guinea', 'Peru', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Rwanda', 'Saudi Arabia', 'Senegal', 'Slovenia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Tajikistan', 'Thailand', 'Tunisia', 'Turkey', 'Uganda', 'Ukraine', 'United Kingdom', 'Uruguay', 'Zambia', 'Zimbabwe']

Number of Countries: 101

In [12]:
print("Crops:")
print(sorted(yield_df["Item"].unique()))

print("\nNumber of Crops:", yield_df["Item"].nunique())

Crops:
['Cassava', 'Maize', 'Plantains and others', 'Potatoes', 'Rice, paddy', 'Sorghum', 'Soybeans', 'Sweet potatoes', 'Wheat', 'Yams']

Number of Crops: 10

In [13]:
print("Years")
print(sorted(yield_df["Year"].unique()))

Years
[np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013)]

In [14]:
print("Year-wise Record Count:\n")
print(yield_df["Year"].value_counts().sort_index())

Year-wise Record Count:

Year
1990    1164
1991    1164
1992    1219
1993    1223
1994    1221
1995    1222
1996    1222
1997    1224
1998    1224
1999    1223
2000    1230
2001    1229
2002    1228
2004    1234
2005    1235
2006    1243
2007    1242
2008    1244
2009    1242
2010    1245
2011    1245
2012    1260
2013    1259
Name: count, dtype: int64

## Summary 

1. Loaded the Crop Yield dataset and related source datasets.

2. Examined dataset dimensions, data types, missing values, and duplicate records.

3. Performed initial preprocessing and removed unnecessary columns.

4. Prepared the final cleaned dataset (yield_df) for analysis and model development.